@startuml Tetris

class Campo {
    - piezas : Piezas
    - indNewPieza : int
    - indColorNewPieza : int
    - newPiezaColor : sf::Color
    - indX : int
    - indY : int
    - timer : int
    - limitTimer : int
    - tablero : int[][]
    - formaTablero : sf::RectangleShape[][]

    + Campo()
    + InstalarPieza() : bool
    + ActTablero() : bool
    + ActColoresTablero() : void
    + ActLimitTimer(l : int) : void
    + RotarPieza() : void
    + Right() : void
    + Left() : void
    + draw(rt : sf::RenderTarget &, rs : sf::RenderStates) const : void
    + Linea() : int
}

class InterfazUsuario {
    - font : Font
    - scoreText : Text
    - scoreTextTitle : Text
    - maxScoreTextTitle : Text
    - maxScoreText : Text
    - gameOverText : Text
    - textTETRIS : Text
    - newScoreText : Text
    - newScore : bool
    - gameOver : bool

    + InterfazUsuario()
    + SetMaxScore(int) : void
    + SetScore(int) : void
    + GameOver() : void
    + NewScore() : void
    + draw(RenderTarget&, RenderStates) const : void

}

class Juego {
    - campo : Campo
    - interfazUsuario : InterfazUsuario
    - sonido : Sonidos
    - window : sf::RenderWindow*
    - heigt : int
    - width : int
    - ev : sf::Event
    - right : int
    - left : int
    - up : int
    - score : int
    - maxScore : int
    - vida : bool

    + Juego()
    + ~Juego()
    + Running() : bool
    + pollEventos() : void
    + actualizar() : void
    + renderizar() : void

    - iniciaVariables() : void
    - iniciaVentana() : void
}

class Piezas {
    - piezas : vector<vector<vector<bool>>>

    + Piezas()
    + ConsultaPieza(int) : vector<vector<bool>>
    + RotarPz(int) : void
    + DesrotarPz(int) : void
}

class Refresh {
    + Refresh()
    + virtual Actualizar() : void = 0
    + ~Refresh()
}

class Sonidos {
    - musica : Music
    - lineaSonido : Sound
    - nuevoRecordSonido : Sound
    - gameOverSonido : Sound
    - lineaBuffer : SoundBuffer
    - nuevoRecordBuffer : SoundBuffer
    - gameOverBuffer : SoundBuffer

    + Sonidos()
    + PlayMusic() : void
    + PauseMusic() : void
    + PlayLine() : void
    + PlayGameOver() : void
    + PlayNewScore() : void
}

Juego "1" *-- "1" Campo: campo 
Juego "1" *-- "1" InterfazUsuario: interfazUsuario 
Juego "1" *-- "4" Sonidos: sonido 
Campo "1" *-- "*" Piezas: piezas

@enduml